apiVersion: apps/v1
kind: Deployment
metadata:
  name: crdconfigmap
  labels:
    app: crdconfigmap
spec:
  selector:
    matchLabels:
      app: crdconfigmap
  template:
    metadata:
      labels:
        app: crdconfigmap
    spec:
      containers:
      - name: proxycontainer
        # image: lachlanevenson/k8s-kubectl
        image: bitnami/kubectl
        command: ["kubectl","proxy","--port=8001"]
      - name: app
        image: <Image name>
        env:
          - name: res_namespace
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace